// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using borsvarlden.Models;

namespace borsvarlden.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("borsvarlden.Models.FinwireCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinwireCompanies");
                });

            modelBuilder.Entity("borsvarlden.Models.FinwireNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinautoPassed")
                        .HasColumnType("bit");

                    b.Property<bool>("FinautoPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathRelative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinwireNews");
                });

            modelBuilder.Entity("borsvarlden.Models.FinwireNew2FinwireCompany", b =>
                {
                    b.Property<int>("FinwireNewId")
                        .HasColumnType("int");

                    b.Property<int>("FinwareCompanyId")
                        .HasColumnType("int");

                    b.HasKey("FinwireNewId", "FinwareCompanyId");

                    b.HasIndex("FinwareCompanyId");

                    b.ToTable("FinwireNew2FinwireCompany");
                });

            modelBuilder.Entity("borsvarlden.Models.FinwireNew2FirnwireSocialTag", b =>
                {
                    b.Property<int>("FinwireSocialTagId")
                        .HasColumnType("int");

                    b.Property<int>("FinwireNewId")
                        .HasColumnType("int");

                    b.HasKey("FinwireSocialTagId", "FinwireNewId");

                    b.HasIndex("FinwireNewId");

                    b.ToTable("FinwireNew2FirnwireSocialTag");
                });

            modelBuilder.Entity("borsvarlden.Models.FinwireSocialTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinwireSocialTags");
                });

            modelBuilder.Entity("borsvarlden.Models.FinwireNew2FinwireCompany", b =>
                {
                    b.HasOne("borsvarlden.Models.FinwireCompany", "FinwireCompany")
                        .WithMany("FinwireNew2FinwireCompanies")
                        .HasForeignKey("FinwareCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("borsvarlden.Models.FinwireNew", "FinwireNew")
                        .WithMany("FinwireNew2FinwireCompanies")
                        .HasForeignKey("FinwareCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("borsvarlden.Models.FinwireNew2FirnwireSocialTag", b =>
                {
                    b.HasOne("borsvarlden.Models.FinwireNew", "FinwireNew")
                        .WithMany("FinwireNew2FirnwireSocialTags")
                        .HasForeignKey("FinwireNewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("borsvarlden.Models.FinwireSocialTag", "FinwireSocialTag")
                        .WithMany("FinwireNew2FirnwireSocialTags")
                        .HasForeignKey("FinwireSocialTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
